/**
 * Icon Name Mapping
 *
 * Maps icon names (lowercase-hyphen, lucide-era vocabulary) to hugeicons
 * glyph data. This file has no dependencies to avoid circular imports
 */
import {
  Infinity01Icon as InfinityIcon,
  Activity01Icon as Activity,
  ScreenRotationIcon as Airplay,
  BadgeCentIcon as BadgeCent,
  BarChartIcon as BarChart,
  BarChartIcon as BarChart3,
  BlocksIcon as Blocks,
  BookBookmark01Icon as BookMarked,
  BookOpen01Icon as BookOpen,
  BotIcon as Bot,
  BoxIcon as Box,
  ChartGanttIcon as ChartGantt,
  ChevronsLeftRightEllipsisIcon as ChevronsLeftRightEllipsis,
  CircleDollarSignIcon as CircleDollarSign,
  CirclePileIcon as CirclePile,
  CodeIcon as Code,
  Coins01Icon as Coins,
  CommandIcon as Command,
  CompassIcon as Compass,
  ContentWritingIcon as ContentWriting,
  DatabaseIcon as Database,
  DiffIcon as Diff,
  FolderClosedIcon as Folder,
  FolderCodeIcon as FolderCode,
  FolderKanbanIcon as FolderKanban,
  FuelIcon as Fuel,
  InternetIcon as Globe,
  WorkHistoryIcon as History,
  Home01Icon as Home,
  type IconSvgElement,
  IdCardIcon as IdCard,
  InboxIcon as Inbox,
  KanbanIcon as Kanban,
  Key02Icon as KeyRound,
  LayoutListIcon as LayoutList,
  BulbIcon as Lightbulb,
  ListTodoIcon as ListTodo,
  Location01Icon as MapPin,
  Message01Icon as MessageSquare,
  HierarchyCircle01Icon as Network,
  PackageDeliveredIcon as PackageCheck,
  PlayIcon as Play,
  PlayCircleIcon as PlayCircle,
  Plug01Icon as Plug,
  Add01Icon as Plus,
  Radar01Icon as Radar,
  RocketIcon as Rocket,
  Search01Icon as Search,
  Search02Icon as SearchCode,
  ServerStack01Icon as Server,
  Settings01Icon as Settings,
  SparklesIcon as Sparkles,
  Store01Icon as Store,
  ComputerTerminal01Icon as Terminal,
  Ticket01Icon as Ticket,
  UserMultipleIcon as Users,
  Wallet01Icon as Wallet,
  MagicWand02Icon as Wand2,
  WorkflowCircle01Icon as Workflow,
} from "@src/icons";

/**
 * Maps icon names to their corresponding hugeicons glyphs
 * Useful for dynamic icon rendering
 */
export const ICON_NAME_MAP: Record<string, IconSvgElement | null> = {
  folder: Folder,
  "message-square": MessageSquare,
  code: Code,
  "content-writing": ContentWriting,
  "folder-code": FolderCode,
  terminal: Terminal,
  globe: Globe,
  "file-text": BookOpen,
  "book-open": BookOpen,
  "book-marked": BookMarked,
  bot: Bot,
  plus: Plus,
  "plus-circle": Plus,
  play: Play,
  "play-circle": PlayCircle,
  settings: Settings,
  cog: Settings,
  bolt: Settings,
  "bar-chart": BarChart,
  "bar-chart-3": BarChart3,
  server: Server,
  command: Command,
  compass: Compass,
  search: Search,
  "search-code": SearchCode,
  "chart-gantt": ChartGantt,
  box: Box,
  coins: Coins,
  database: Database,
  "git-compare-arrows": Diff,
  diff: Diff,
  history: History,
  lightbulb: Lightbulb,
  sparkles: Sparkles,
  ticket: Ticket,
  "key-round": KeyRound,
  "id-card": IdCard,
  infinity: InfinityIcon,
  "layout-list": LayoutList,
  "list-todo": ListTodo,
  "folder-kanban": FolderKanban,
  radar: Radar,
  activity: Activity,
  users: Users,
  kanban: Kanban,
  home: Home,
  inbox: Inbox,
  wallet: Wallet,
  "badge-cent": BadgeCent,
  "circle-dollar-sign": CircleDollarSign,
  blocks: Blocks,
  "package-check": PackageCheck,
  plug: Plug,
  rocket: Rocket,
  "chevrons-left-right-ellipsis": ChevronsLeftRightEllipsis,
  store: Store,
  fuel: Fuel,
  workflow: Workflow,
  "map-pin": MapPin,
  network: Network,
  airplay: Airplay,
  "circle-pile": CirclePile,
  "wand-2": Wand2,
};
